#
# Patch to update the deployment to support SSL
# of the internal deployed nginx server
# - scheme: HTTPS
# - volumeMounts: hawtio-online-tls-serving
# - env: SSL variables populated
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hawtio-online
spec:
  template:
    spec:
      containers:
        - name: hawtio-online
          env:
          - name: HAWTIO_ONLINE_SSL_KEY
            value: /etc/tls/private/serving/tls.key
          - name: HAWTIO_ONLINE_SSL_CERTIFICATE
            value: /etc/tls/private/serving/tls.crt
          livenessProbe:
            httpGet:
              path: /online
              port: nginx
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /online
              port: nginx
              scheme: HTTPS
          volumeMounts:
            - name: hawtio-online-tls-serving
              mountPath: /etc/tls/private/serving
        - name: hawtio-online-gateway
          env:
            - name: HAWTIO_ONLINE_GATEWAY_WEB_SERVER
              value: https://localhost:8443
            - name: HAWTIO_ONLINE_GATEWAY_SSL_KEY
              value: /etc/tls/private/serving/tls.key
            - name: HAWTIO_ONLINE_GATEWAY_SSL_CERTIFICATE
              value: /etc/tls/private/serving/tls.crt
            - name: HAWTIO_ONLINE_GATEWAY_SSL_CERTIFICATE_CA
              value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          livenessProbe:
            httpGet:
              path: /status
              port: express
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /status
              port: express
              scheme: HTTPS
          volumeMounts:
            - name: hawtio-online-tls-serving
              mountPath: /etc/tls/private/serving
      volumes:
        - name: hawtio-online-tls-serving
          secret:
            secretName: hawtio-online-tls-serving
