{{- if and (eq .Values.mode "namespace") (eq .Values.clusterType "k8s") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "hawtio-online.app.labels" .Values.online | indent 4 }}
  name: {{ .Values.online.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
