#
# Global ARGs required
#
# Version
ARG HAWTIO_ONLINE_VERSION=2.5.0
# The hawtio namespace for the build images
ARG HAWTIO_NAMESPACE="rhbac-4"
# Name of the application without the main registry (used in labels)
ARG HAWTIO_ONLINE_IMAGE_LABEL_NAME=${HAWTIO_NAMESPACE}/hawtio-rhel9

FROM registry.access.redhat.com/hi/nodejs:22 as staging

#
# Ensure that yarn is installed
#
USER root
RUN command -v yarn || npm i -g yarn

WORKDIR /hawtio-online

COPY package.json yarn.lock ./
COPY .yarnrc.yml ./
COPY packages/ packages/
COPY .yarn/plugins .yarn/plugins
COPY .yarn/releases .yarn/releases

RUN yarn install
RUN yarn build

COPY Makefile ./
RUN cat Makefile | grep ^VERSION.*[0-9] >> hawtio-online-version

#######################################################

#
# Final Image
#
FROM registry.access.redhat.com/ubi9-minimal:9.8

#
# From global variables
#
ARG HAWTIO_ONLINE_VERSION
ARG HAWTIO_NAMESPACE
ARG HAWTIO_ONLINE_IMAGE_LABEL_NAME

#
# nginx environment
#
ARG NGINX_ETC=/etc/nginx
ARG NGINX_CONFIG=${NGINX_ETC}/nginx.conf
ARG NGINX_CACHE=/var/cache/nginx
ARG NGINX_LOG=/var/log/nginx
ARG NGINX_SHARE=/usr/share/nginx
ARG NGINX_HTML=${NGINX_SHARE}/html
ARG NGINX_ONLINE=${NGINX_HTML}/online

# The user id for nginx on RHEL
ARG NGINX_USER=999

#
# Version of nginx
#
ARG NGINX_MAJOR_VERSION=1
ARG NGINX_MINOR_VERSION=22
ARG NGINX_BUILD_VERSION=1

#
# Hawtio environment
#
# Location of hawtio-online in staging container (same as WORKDIR)
ARG HAWTIO_ONLINE_STAGING_DIR=/hawtio-online
ARG HAWTIO_ONLINE_STAGING_BUILD_DIR=${HAWTIO_ONLINE_STAGING_DIR}/packages/online-shell/build
ARG HAWTIO_ONLINE_DOCKER_DIR=docker
ARG HAWTIO_ONLINE_BRANDING_DIR=branding
ARG HAWTIO_DESCRIPTON="The Red Hat build of HawtIO helps discovering and managing Jolokia-monitored applications deployed on OpenShift."

LABEL com.redhat.component="hawtio-container" \
    description="${HAWTIO_DESCRIPTION}" \
    io.k8s.description="${HAWTIO_DESCRIPTION}" \
    io.k8s.display-name="Red Hat build of HawtIO" \
    io.openshift.expose-services="8443:https" \
    io.openshift.tags="hawtio,jolokia" \
    maintainer="Paul Richardson <Paul.Richardson3@ibm.com>" \
    name="${HAWTIO_ONLINE_IMAGE_LABEL_NAME}" \
    summary="${HAWTIO_DESCRIPTION}" \
    version="${HAWTIO_ONLINE_VERSION}" \
    version.file="/opt/hawtio/hawtio-online-version"

#
# Perform an upgrade of all packages to ensure
# any outstanding packages are updates from the
# base images
#
RUN microdnf upgrade -y

#
# Install gettext for envsubst
#
RUN microdnf install -y gettext

#
# Install nginx and cleanup
#
RUN microdnf -y module enable nginx:${NGINX_MAJOR_VERSION}.${NGINX_MINOR_VERSION}
RUN microdnf install -y nginx-${NGINX_MAJOR_VERSION}.${NGINX_MINOR_VERSION}.${NGINX_BUILD_VERSION} && \
    microdnf clean all

#
# Modify the nginx configuration
#
# Forward request and error logs to docker log collector
# - Change pid file location & remove nginx user & change port to 8080
# - modify perms for non-root runtime
#
RUN mkdir -p ${NGINX_CACHE}/pods ${NGINX_CACHE}/rbac ${NGINX_CACHE}/rbac2 && \
    ln -sf /dev/stdout ${NGINX_LOG}/access.log && \
    ln -sf /dev/stderr ${NGINX_LOG}/error.log && \
    sed -i "s~pid.*~pid ${NGINX_CACHE}/nginx.pid;~g" ${NGINX_CONFIG} && \
    sed -i '/listen/s%80%8000%' ${NGINX_CONFIG} && \
    sed -i -e '/user/!b' -e '/nginx/!b' -e '/nginx/d' ${NGINX_CONFIG} && \
    chown -R ${NGINX_USER} ${NGINX_CACHE} ${NGINX_ETC} ${NGINX_LOG} ${NGINX_SHARE} && \
    chmod -R g=u ${NGINX_CACHE} ${NGINX_ETC} ${NGINX_LOG}

#
# Remove default installed boilerplate
#
RUN rm -f ${NGINX_ETC}/conf.d/default.conf \
          ${NGINX_HTML}/index.html

#
# Update locations of osconsole config
#
RUN mkdir -p ${NGINX_ONLINE}/osconsole && \
    touch ${NGINX_ONLINE}/osconsole/config.json && \
    chown ${NGINX_USER} ${NGINX_ONLINE}/osconsole/config.json && \
    chmod g=u ${NGINX_ONLINE}/osconsole/config.json

#
# Copy include directory
#
COPY ${HAWTIO_ONLINE_DOCKER_DIR}/includes ${NGINX_ETC}/includes

#
# Copy docker config files over
#
COPY ${HAWTIO_ONLINE_DOCKER_DIR}/nginx-gateway.conf.template \
    ${HAWTIO_ONLINE_DOCKER_DIR}/osconsole/config.sh \
    ${HAWTIO_ONLINE_DOCKER_DIR}/nginx.sh \
    /

#
# Copy error pages
#
COPY ${HAWTIO_ONLINE_DOCKER_DIR}/hawtio-?0?.html ${NGINX_HTML}/

#
# Copy built hawtio-online app
#
COPY --from=staging ${HAWTIO_ONLINE_STAGING_BUILD_DIR} ${NGINX_ONLINE}/

#
# Copy custom product branding (overwrites existing brought from staging build)
#
COPY ${HAWTIO_ONLINE_BRANDING_DIR}/ ${NGINX_ONLINE}/

#
# Copy licenses and version file
#
RUN mkdir -p /opt/hawtio/licenses
COPY --from=staging ${HAWTIO_ONLINE_STAGING_DIR}/docker/licenses \
    ${HAWTIO_ONLINE_STAGING_DIR}/hawtio-online-version \
    /opt/hawtio/

EXPOSE 8443

USER ${NGINX_USER}

CMD ["./nginx.sh"]
