FROM docker.io/node:20-alpine as builder

WORKDIR /hawtio-online

COPY package.json yarn.lock ./
COPY .yarnrc.yml ./
COPY packages/ packages/
COPY .yarn/plugins .yarn/plugins
COPY .yarn/releases .yarn/releases

RUN yarn install
RUN yarn build

# Build stage to extract envsubst
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10 as envsubst

RUN microdnf -y install gettext

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10

ENV NGINX_VERSION 1.20.2-1.el8

LABEL name="nginxinc/nginx" \
    vendor="NGINX Inc." \
    version="${NGINX_VERSION}" \
    release="1" \
    summary="NGINX" \
    description="nginx will do ....."
## Required labels above - recommended below
LABEL url="https://www.nginx.com/" \
    io.k8s.display-name="NGINX" \
    io.openshift.expose-services="8443:https" \
    io.openshift.tags="nginx,nginxinc"

COPY docker/nginx.repo /etc/yum.repos.d/nginx.repo

RUN curl -sO https://nginx.org/keys/nginx_signing.key && \
    rpm --import ./nginx_signing.key && \
    microdnf -y install --setopt=tsflags=nodocs nginx-${NGINX_VERSION}.ngx && \
    rm -f ./nginx_signing.key && \
    microdnf clean all

# forward request and error logs to docker log collector
# - Change pid file location & remove nginx user & change port to 8080
# - modify perms for non-root runtime
RUN ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log && \
    sed -i 's~/var/run/nginx.pid~/var/cache/nginx/nginx.pid~g' /etc/nginx/nginx.conf && \
    sed -i -e '/user/!b' -e '/nginx/!b' -e '/nginx/d' /etc/nginx/nginx.conf && \
    sed -i 's~/var/log/nginx/error.log warn~/var/log/nginx/error.log info~g' /etc/nginx/nginx.conf && \
    chown -R 998 /var/cache/nginx /etc/nginx && \
    rm -f /etc/nginx/conf.d/default.conf && \
    chmod -R g=u /var/cache/nginx /etc/nginx

EXPOSE 8443

## Add symbolic link to config.json to avoid mounting issues
#RUN ln -sf /usr/share/nginx/html/config.json /usr/share/nginx/html/config.json

RUN rm /usr/share/nginx/html/index.html

RUN mkdir -p /usr/share/nginx/html/online/osconsole && \
    touch /usr/share/nginx/html/online/osconsole/config.json && \
    chown 998 /usr/share/nginx/html/online/osconsole/config.json && \
    chmod g=u /usr/share/nginx/html/online/osconsole/config.json

COPY docker/nginx-gateway.conf.template docker/osconsole/config.sh docker/nginx.sh /

# Copy error pages
COPY docker/hawtio-?0?.html /usr/share/nginx/html/

# Copy licenses
RUN mkdir -p /opt/hawtio/licenses
COPY --from=builder /hawtio-online/docker/licenses /opt/hawtio/licenses

COPY --from=builder /hawtio-online/packages/online-shell/build /usr/share/nginx/html/online/
COPY --from=envsubst /usr/bin/envsubst /usr/local/bin/

USER 998

CMD ["./nginx.sh"]
