apiVersion: apps/v1
kind: Deployment
metadata:
  name: hawtio-online
spec:
  template:
    spec:
      containers:
        - name: hawtio-online
          env:
            - name: HAWTIO_ONLINE_AUTH
              value: form
            - name: HAWTIO_ONLINE_MODE
              value: cluster
