apiVersion: apps/v1
kind: Deployment
metadata:
  name: hawtio-online
  labels:
    app: hawtio
    deployment: hawtio-online
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hawtio
      deployment: hawtio-online
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: hawtio
        deployment: hawtio-online
    spec:
      containers:
        - image: quay.io/hawtio/online
          imagePullPolicy: Always
          name: hawtio-online
          ports:
            - name: nginx
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /online
              port: nginx
              scheme: HTTPS
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /online
              port: nginx
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
          env:
            - name: HAWTIO_ONLINE_RBAC_ACL
              value: /etc/hawtio/rbac/ACL.yaml
          resources:
            requests:
              cpu: "0.2"
              memory: 32Mi
            limits:
              cpu: "1.0"
              memory: 500Mi
          volumeMounts:
            - name: hawtio-rbac
              mountPath: /etc/hawtio/rbac
            - name: hawtio-online-tls-serving
              mountPath: /etc/tls/private/serving
      volumes:
        - name: hawtio-rbac
          configMap:
            name: hawtio-rbac
        - name: hawtio-online-tls-serving
          secret:
            secretName: hawtio-online-tls-serving
