apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap-hawtio-rbac.yml
- deployment.yml
- service.yml
- configmap-hawtio-online.yml
patches:
- path: ../patches/patch-hawtconfig-configmap.yml
  target:
    kind: Deployment
