apiVersion: v1
kind: Service
metadata:
  name: hawtio-online
  labels:
    app: hawtio
spec:
  type: NodePort
  ports:
    - name: hawtio-online
      port: 443
      protocol: TCP
      targetPort: nginx
  selector:
    app: hawtio
    deployment: hawtio-online
