{{- if eq .Values.clusterType "k8s" }}
apiVersion: v1
data:
{{ include "hawtio-online.serving.gen-cert" . }}
kind: Secret
metadata:
  name: {{ .Values.online.secrets.serving.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "hawtio-online.app.labels" .Values.online | indent 4 }}
type: kubernetes.io/tls
{{- end }}
