apiVersion: v1
kind: Service
metadata:
  annotations:
{{- if eq .Values.clusterType "openshift" }}
    service.beta.openshift.io/serving-cert-secret-name: {{ .Values.online.secrets.serving.name }}
{{- end }}
{{- with .Values.online.service.annotations }}
  {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
{{ include "hawtio-online.app.labels" .Values.online | indent 4 }}
  name: {{ .Values.online.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: {{ .Values.online.name }}
      port: {{ include "hawtio-online.service.port" .Values }}
      protocol: TCP
      targetPort: nginx
  selector:
{{ include "hawtio-online.app.selector" .Values.online | indent 4 }}
  type: {{ .Values.online.service.type }}
