{{- if and (eq .Values.mode "namespace") (eq .Values.clusterType "openshift") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.route: '{"kind": "OAuthRedirectReference", "apiVersion": "v1", "reference": {"kind": "Route", "name": "hawtio-online"}}'
    serviceaccounts.openshift.io/oauth-redirecturi.route: https://
  labels:
{{ include "hawtio-online.app.labels" .Values.online | indent 4 }}
  name: {{ .Values.online.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
