#!/bin/bash

REGISTRY=registry.redhat.io
REG_NAMESPACE=rhbac-4
ONLINE_IMAGE_NAME=hawtio-rhel9
ONLINE_GATEWAY_IMAGE_NAME=hawtio-gateway-rhel9
VERSION=2.3.0

CLUSTER_TYPE=openshift
MODE=cluster
NAMESPACE=hawtio-dev
OS_CONSOLE_URL=https://console-openshift-console.apps-crc.testing \
SSL=true
CUSTOM_IMAGE=${REGISTRY}/${REG_NAMESPACE}/${ONLINE_IMAGE_NAME}
CUSTOM_VERSION=${VERSION}
CUSTOM_GATEWAY_IMAGE=${REGISTRY}/${REG_NAMESPACE}/${ONLINE_GATEWAY_IMAGE_NAME}
CUSTOM_GATEWAY_VERSION=${VERSION}
DRY_RUN=false

echo "CLUSTER_TYPE ${CLUSTER_TYPE}"
echo "MODE ${MODE}"
echo "NAMESPACE ${NAMESPACE}"
echo "OS_CONSOLE_URL ${OS_CONSOLE_URL}"
echo "SSL ${SSL}"
echo "CUSTOM_IMAGE ${CUSTOM_IMAGE}"
echo "CUSTOM_VERSION ${CUSTOM_VERSION}"
echo "CUSTOM_GATEWAY_IMAGE ${CUSTOM_GATEWAY_IMAGE}"
echo "CUSTOM_GATEWAY_VERSION ${CUSTOM_GATEWAY_VERSION}"
echo "DRY_RUN ${DRY_RUN}"

CLUSTER_TYPE=${CLUSTER_TYPE} \
  MODE=${MODE} \
  NAMESPACE=${NAMESPACE} \
  OS_CONSOLE_URL=${OS_CONSOLE_URL} \
  INTERNAL_SERVER_SSL=${SSL} \
  CUSTOM_IMAGE=${CUSTOM_IMAGE} \
  CUSTOM_VERSION=${CUSTOM_VERSION} \
  CUSTOM_GATEWAY_IMAGE=${CUSTOM_GATEWAY_IMAGE} \
  CUSTOM_GATEWAY_VERSION=${CUSTOM_GATEWAY_VERSION} \
  MASK_IP_ADDRESSES=${MASK_IP_ADDRESSES} \
  DRY_RUN=${DRY_RUN} \
  make install
