apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bases/configmap-hawtio-online.yml
  - bases/configmap-hawtio-integration.yml
  - bases/configmap-hawtio-rbac.yml
  - bases/deployment.yml
  - bases/service.yml
  - bases/serviceaccount.yml
