apiVersion: v1
kind: Service
metadata:
  name: test-jolokia
  namespace: <NAMESPACE>
spec:
  ports:
    - port: <JOLOKIA-PORT>
      protocol: TCP
      targetPort: <JOLOKIA-PORT>
  selector:
    app: <SELECT-POD-LABEL>
  type: ClusterIP
