apiVersion: v1
kind: ConfigMap
metadata:
  name: hawtio-online
data:
  hawtconfig.json: |
    {
      "about": {
        "title": "Hawtio OpenShift Console",
        "productInfo": [],
        "additionalInfo": "The Hawtio OpenShift Console eases the discovery and management of 'hawtio-enabled' applications deployed on OpenShift.",
        "copyright": ""
      },
      "branding": {
        "appName": "Hawtio OpenShift Console",
        "appLogoUrl": "img/hawtio-logo.svg"
      },
      "disabledRoutes": []
    }
