apiVersion: v1
kind: Service
metadata:
  name: hawtio-online
  labels:
    app: hawtio
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: hawtio-online-tls-serving
spec:
  type: NodePort
  ports:
    - name: hawtio-online
      port: 443
      protocol: TCP
      targetPort: nginx
  selector:
    app: hawtio
    deployment: hawtio-online
