apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../route.yml
- ../../base

patchesStrategicMerge:
- ../patch-deployment.yml
- ../patch-service.yml
- patch-deployment-env.yml

# OCP should always use internal SSL
patches:
- path: ../../patches/patch-deployment-ssl-serving-secret.yml
  target:
    kind: Deployment
- path: ../../patches/patch-deployment-ssl-ports.yml
  target:
    kind: Deployment
- path: ../../patches/patch-service-ssl-ports.yml
  target:
    kind: Service
