apiVersion: apps/v1
kind: Deployment
metadata:
  name: hawtio-online
spec:
  template:
    spec:
      containers:
        - name: hawtio-online
          env:
            - name: HAWTIO_ONLINE_AUTH
              value: oauth
            - name: HAWTIO_ONLINE_MODE
              value: namespace
            - name: HAWTIO_ONLINE_GATEWAY
              value: 'true'
            - name: OPENSHIFT_WEB_CONSOLE_URL
              value: ${OPENSHIFT_WEB_CONSOLE_URL}
            - name: OPENSHIFT_CLUSTER_VERSION
              value: '4'
          volumeMounts:
            - name: hawtio-online-tls-proxying
              mountPath: /etc/tls/private/proxying
      volumes:
        - name: hawtio-online-tls-proxying
          secret:
            secretName: hawtio-online-tls-proxying
