name: Audit Downstream Branches

on:
  schedule:
    # Run it every Sunday
    - cron: '0 0 * * 0'
  # Allow manual run if necessary
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ 2.x-redhat, 2.3.x-redhat ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ matrix.branch }}
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Enable yarn v4
        run: |
          corepack enable
          yarn -v
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v5
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Audit
        run: yarn npm audit --all
