name: Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    steps:
      - name: Install QEMU static binaries for Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build Hawtio image on ${{matrix.arch}}
        run: |
          ARCHS=${{matrix.arch}} make image
      - name: Build Hawtio Gateway image on ${{matrix.arch}}
        run: |
          ARCHS=${{matrix.arch}} make image-gateway
      - name: Display images
        run: |
          make list-images
